name: server
description: A simple command-line application.
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  socket_io: ^0.9.4
  meta: ^1.3.0
  common:
    path: ../common
dev_dependencies:
  pedantic: ^1.9.0